name: Update assets
on:
  push:
    branches:
      - "stable"

jobs:
  tag:
    name: Push on stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: WordPress Plugin Assets Update
        id: deploy
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
